In [129]:
import numpy as np


In [130]:
def F(x): #x=[x1,x2,x3,...,xn]
    y = np.zeros((40,40))
    z = np.zeros((40,40))
    for n in range(40):
        z[n][n] = -1
        z[n][np.mod(n+1+1,40)-1] = x[np.mod(n-1+1,40)-1]
        z[n][np.mod(n-1+1,40)-1] = x[np.mod(n+1+1,40)-1]
        #print(np.mod(n-2+1,40)-1)
        z[n][np.mod(n-2+1,40)-1] = -1*x[np.mod(n+1+1,40)-1]
    return z

In [133]:
x = np.arange(40)
#print(x)
w = F(x) 
print(w)

[[-1. 39.  0. ...  0. -1.  1.]
 [ 2. -1.  0. ...  0.  0. -2.]
 [-3.  3. -1. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ... -1. 36.  0.]
 [ 0.  0.  0. ... 39. -1. 37.]
 [38.  0.  0. ...  0.  0. -1.]]


In [132]:
x = [0,1,2,3]
print(x)

[0, 1, 2, 3]


In [123]:
y = [0,0,0,0]
z = [0,0,0,0]
n = 0
z[n] = -1 
z[np.mod(n+1+1,40)-1] = x[np.mod(n-1+1,40)-1]
z[np.mod(n-1+1,40)-1] = x[np.mod(n+1+1,40)-1]
print(np.mod(n-2+1,40)-1)
z[np.mod(n-2+1,40)-1] = -1*x[np.mod(n+1+1,40)-1]

print(z)

2
[-1, 3, -1, 1]


In [23]:
np.matmul(np.reshape(y,[4,1]), np.transpose(np.reshape(y,[4,1])))

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 4]])